Add Process ID to formatters
IBM/alchemy-logging pull request #463
Opened 2024-10-23 13:34 UTC by HonakerM

## Description

This PR adds the ability for formatters to optionally include the process_id in the log message. This is useful for multi-process applications. 

## Changes

Add new option to python alog.configure.

## Testing

Tested locally

## Related Issue(s)

List any issues related to this PR

2024-10-23 14:42 UTC, gabe-l-hart requested changes
Two small nits. Nice addition!

2024-10-23 14:42 UTC, gabe-l-hart commented on src/python/alog/alog.py
> +import os
NIT: Please sort these alphabetically

2024-10-23 14:42 UTC, gabe-l-hart commented on src/python/alog/alog.py
> +    process_id: bool =False,
```suggestion
    thread_id: bool = False,
    handler_generator: Optional[Callable[[], logging.Handler]] = None,
    process_id: bool = False,
```

2024-10-23 18:31 UTC, gabe-l-hart requested changes
Ok, nice! I think there are a few more things we should add to make this maximally useful:

1. It should be handled in the pretty formatter. I'd suggest adding it right next to the `thread_id` ([here](https://github.com/IBM/alchemy-logging/blob/main/src/python/alog/alog.py#L239)) so that it formats as `:<thread_id>:P<proc_id>`
2. We should add unit tests. This would look like adding it to the [pretty print parsing](https://github.com/IBM/alchemy-logging/blob/main/src/python/tests/test_alog.py#L71), then replicating [the tests for `thread_id`](https://github.com/IBM/alchemy-logging/blob/main/src/python/tests/test_alog.py#L363) and making sure we handle having both/one/neither.

2024-10-23 19:14 UTC, HonakerM commented
@gabe-l-hart darn you trying to enforce good code etiquette. Let me push a commit

2024-10-24 20:47 UTC, gabe-l-hart approved these changes
Thanks for putting up with me Casey!

2024-10-24 20:47 UTC, merged